export const AVERAGE_MEASUREMENTS_REQUEST = "AVERAGE_MEASUREMENTS_REQUEST";
export const AVERAGE_MEASUREMENTS_SUCCESS = "AVERAGE_MEASUREMENTS_SUCCESS";
export const AVERAGE_MEASUREMENTS_FAILURE = "AVERAGE_MEASUREMENTS_FAILURE";

export const MEASUREMENTS_REQUEST = "MEASUREMENTS_REQUEST";
export const MEASUREMENTS_SUCCESS = "MEASUREMENTS_SUCCESS";
export const MEASUREMENTS_FAILURE = "MEASUREMENTS_FAILURE";
