export const AVERAGE_MEASUREMENTS_REQUEST = "AVERAGE_MEASUREMENTS_REQUEST";
export const AVERAGE_MEASUREMENTS_SUCCESS = "AVERAGE_MEASUREMENTS_SUCCESS";
export const AVERAGE_MEASUREMENTS_FAILURE = "AVERAGE_MEASUREMENTS_FAILURE";

export const MEASUREMENTS_REQUEST = "MEASUREMENTS_REQUEST";
export const MEASUREMENTS_SUCCESS = "MEASUREMENTS_SUCCESS";
export const MEASUREMENTS_FAILURE = "MEASUREMENTS_FAILURE";

export const TEMPERATURE_FILTER = "TEMPERATURE_FILTER";
export const HUMIDITY_FILTER = "HUMIDITY_FILTER";
export const POLLUTION_FILTER = "POLLUTION_FILTER";
